### ISSUE TITLE
CRITS domain view

### ISSUE THREAD

**Issue by taylormd** [crits/crits#349]
I have recently upgraded from CRITS 3.0 to the current version. When I browse to the 
https://148.93.12.63/domains/list/ and a box pops up saying "An error occured while communicating to the server." I did check the mongodb and the domains collection is there an all the data is there. I looked to try to find the logs, but was not find able to find any errors related to this. Anyone have any thoughts?

**Comment by jonjonLynch** [comment]
I am experiencing the same issue.  Unfortunately for my team all of our domains are "new" so we cannot see any domains through this view.  @taylormd did you find a fix?  I am still troubleshooting and will post if I come across a solution myself.

**Comment by taylormd** [comment]
No I was not able to get it fixed.

**Comment by jonjonLynch** [comment]
@taylormd  So, the issue for me is a bad domain name added to the database.  I found the error 

"NoReverseMatch at /domains/list/jtlist/Reverse for 'crits.domains.views.domain_detail' with arguments '(u' pn.[redacted].com',)' and keyword arguments '{}' not found. 1 pattern(s) tried: "

I did a CSV dump and noticed the domain had a space in front of it and no other domain has a space.  If I preform a search for the "bad" domain it comes up with an error as expected. If I do a search for a different "good" domain, no error.

Unfortunately for me I have no idea how to delete this database entry.. if you do please let me know.

**Comment by mgoffin** [comment]
From a mongo shell:

use crits
db.domains.count({'domain': ' pn.[redacted].com'})

If that returns one document, change "count" to "findOne" and confirm it's
the document you want to remove. If so, change "findOne" to "remove" and it
will go away.

**Comment by jonjonLynch** [comment]
@mgoffin thank you! The domain was deleted and the error is gone!

**Comment by dsnellgrove** [comment]
@jonjonLynch What version of CRITs were you on when you created the invalid domain name entry? I'm wondering if the issue is:
1) Input validation used to be poor so domain names used in the URL don't match the regex in urls.py
2) Input validation is still poor enough to allow this situation
3) The regex in urls.py is just too restrictive and should be relaxed so that "invalid" domains don't cause the application to crash or a similar workaround provided.

**Comment by jonjonLynch** [comment]
@dsnellgrove we are running 3.1 stable.  I input the bad domain today so I cannot say if it would have been an issue in 3.0.  The original post suggests their DB may have contained a bad input that was not an issue in 3.0 but became one in 3.1.  Although, I am not sure if their issue is in fact the same as mine.  

I could see the issue being an actual DB error because it cannot handle a space.  I am not familiar enough with Mongo to know for sure.

**Comment by dsnellgrove** [comment]
The issue is actually the python code https://github.com/crits/crits/blob/master/crits/domains/urls.py#L7
"NoReverseMatch at /domains/list/jtlist/Reverse for 'crits.domains.views.domain_detail' with arguments '(u' pn.[redacted].com',)' and keyword arguments '{}' not found. 1 pattern(s) tried: " results when it tries to fit a domain with a space into a pattern that only allows \S (non-whitespace-characters). Square peg, round hole, crash. The URL matcher needs to be relaxed or the input validation needs to be improved or some other validation needs to happen during URL construction time or all of that in some way. I leave it to @mgoffin to best decide the approach.

**Comment by taylormd** [comment]
Well it looks like you were right @jonjonLynch. I deleted two domains that had spaces in it and it came back up with no issues. Thanks for all the help!
