### ISSUE TITLE
CRITs API does not support importing emails

### ISSUE THREAD

**Issue by treyka** [crits/crits#363]
I'm trying to import email metadata via the API. After re-reading the docs multiple times and experimenting with carefully constructed  (and apparently compliant) input I've concluded that this functionality is currently broken.

**Comment by dsnellgrove** [comment]
It appears to work for others. Please provide more information supporting your conclusion.

**Comment by treyka** [comment]
Hi, dsnellgrove -

Okay, fair enough...I've tried every variation I can imagine of field uploads and also posting raw. As far as I can see, nothing works.

Can you see anything wrong with the following json? (I'm obviously omitting the authentication bits here...)

<snip>
{'from_address': '<foo@example.com>', 'to': 'bar@example.com', 'upload_type': 'fields', 'date': '2015-01-02 15:10:00+00:00', 'message_id': '<123456789>', 'subject': 'hello, world!'}
</snip>

**Comment by mgoffin** [comment]
The system should provide you with a response and some information in it. It would help to see what that is.

I would also guess that it's complaining because you aren't including a source in your POST. When adding a TLO to the system you'll need to provide source information. This is how the system knows what information a user is/isn't allowed to see. For more information on adding this to your POST, you can check out this link: https://github.com/crits/crits/wiki/Authenticated-API#common-post-parameters.

**Comment by treyka** [comment]
After further experimentation I discovered that 'To' and 'CC' must be a list.
