### ISSUE TITLE
readthedocs

### ISSUE THREAD

**Issue by mgoffin** [crits/crits#429]
I have a readthedocs for CRITs but the build process fails (can't import crits.settings among other problems).

If anyone is familiar with readthedocs and knows how to short-circuit their build process (using MOCK_MODULES or something?) and wants to tackle getting it to generate legit documentation, let me know :)

**Comment by gtback** [comment]
It looks like the import of `crits.settings` is failing because other modules that it needs (Django, MongoEngine, pymongo) aren't available. RTD requires a virtualenv and requirements.txt file to install third party packages like this. It's a bit different for CRITs as a standalone project rather than a library; there's no `setup.py` file. If you create one, you can check for the `READTHEDOCS` environment variable so that people don't see it and try to "install" CRITs locally using that method rather than the bootstrap script.
