### ISSUE TITLE
handle_raw_data_file() return discrepancy

### ISSUE THREAD

**Issue by frbapolkosnik** [crits/crits#433]
At https://github.com/crits/crits/blob/master/crits/raw_data/handlers.py#L323 
handle_raw_data_file() 's comment notes the following:

 :returns: dict with keys:
'success' (boolean),
'message' (str),
'md5' (str) if successful.

but at https://github.com/crits/crits/blob/master/crits/raw_data/handlers.py#L418, 
the actual code does otherwise:

 status = {
'success': True,
'message': 'Uploaded raw_data',
'_id': raw_data.id,
}

Please advise.

**Comment by frbapolkosnik** [comment]
Perhaps these kinds of functions should return the obj just like handle_file() does in the handlers.py for samples. For one it would make it more intuitive to work with different types of objects.

Thanks

**Comment by mgoffin** [comment]
These changes were/are being made for parity between the web, command-line, and API. Work is actively being done so this issue is sort of redundant.

**Comment by frbapolkosnik** [comment]
Ok, but which one do I use?

**Comment by mgoffin** [comment]
The one the code actually does (since docstrings don't actually *do* anything to the processing of the data).

If you want you can submit a PR bringing the docstrings into alignment with what the code does. We always like having accurate docstrings, and if someone is doing work on them and you get yours in first, they'll have to merge your changes into theirs.
