### ISSUE TITLE
Vagrant: No matching sls found for 'mongodb'

### ISSUE THREAD

**Issue by packet-rat** [crits/crits#463]
* Cloned crits Master Branch locally (e.g. /dev/git/crits)
 * cd'd to /dev/git/crits
 * executed git submodule commands to include the mongodb salt formula?
```
git submodule init
git submodule update

vagrant up
```
Kept getting the error:
```
    No matching sls found for 'mongodb' in env 'base'
```
Cloned:  https://github.com/saltstack-formulas/mongodb-formula (it was updated ~ April 16, 2015)
Replaced /dev/git/crits/salt/roots/salt/formulas/mongodb-formula with a copy of the above

repeated git submodule commands:
```
$ git submodule init
$ git submodule update
Submodule path 'salt/roots/salt/formulas/mongodb-formula': checked out '41bea751c6f698c2c5a2a4421189ed6387f8ecd3'

 $ vagrant up
```
Time passes...

```
Summary
-------------
Succeeded: 50 (changed=45)
Failed:     0
-------------
Total states run:     50
```
Life is good.

**Comment by gtback** [comment]
I know I've seen this error before, but I can't seem to reproduce it now, even on a freshly cloned copy of the CRITs repo. Are you sure that the `git submodule init` and `git submodule update` commands didn't give any errors? If I remember, the "no matching sls" error was caused by the submodule not being initialized.
