### ISSUE TITLE
Update CRITs TLDs

### ISSUE THREAD

**Issue by robertsjw** [crits/crits#518]
CRITs does not seem to understand some TLDs.  In particular, I am unable to add a domain with the TLD of .uk

**Comment by mgoffin** [comment]
It only knows that which are in the provided public suffix record uploaded to your system. .uk would be in there so it seems strange you are having the problem. We will most likely need more context around your problem and how to reproduce it.

**Comment by robertsjw** [comment]
So it looks like it works fine if I try and add <subdomain>.<domain>.uk but not if I just add <domain>.uk.

**Comment by mgoffin** [comment]
As per my previous comment, CRITs only knows about the TLDs which are provided in the public suffix record uploaded to your system. You most likely haven't updated your TLD list with the latest one. You can fix this by:

- Going to Nav -> Add New Item -> TLDs
- Follow the on-screen directions
- Restart your web server (there is a fix in master I believe where you don't have to do this but I don't know what code base you are running).

I am able to upload domains like "foo.uk" as I am running a recent version of the suffix. It is updated regularly which is why we added this interface. It gives everyone the ability to keep up with it.

Hope this helps!
