### ISSUE TITLE
Issue with update command, "ImportError: No module named create_sectors"

### ISSUE THREAD

**Issue by armtashjian** [crits/crits#567]
When trying to run the update or prep command on a fresh install of CRITs, I am getting this import error: "ImportError: No module named create_sectors".
It seems as though the crits/core/management/commands/create_sectors.py file no longer exists in the latest commit of CRITs.  I have an instance of CRITs which is a year old and I am able to find the same file.  

Aside from this issue, is there any documentation regarding upgrading CRITs? I am aware of the "UPDATING" file which lists the changes between commits, including the changes that need to be made to the database.  I will be attempting to upgrade an instance of CRITs which is quite old (July/August 2014).  

What I was planning to do was: 
1. Pull down the latest master commit.  
2. Run through the commands in the "UPDATING" file to get the database up to speed.
3. Run manage.py update prep
4. Run manage.py update -a --migrate_all

**Comment by mgoffin** [comment]
Yea. The upgrade and prep scripts tend to not get much love until release time so that should be fixed.

If you are following UPDATING then there is no real need to run `prep` or `upgrade` unless the entry in UPDATING states to do so. Those tools are generally for people following releases.

If you are on master (or the recommended stable_# branch (currently stable_4)) then to keep your system up-to-date, you can simply:

- git pull
- read and apply UPDATING entries since last pull

**Comment by armtashjian** [comment]
Thanks for the info!
