### ISSUE TITLE
Unable to implement fresh install of CRITS under CentOS 6.6 x86_64 version

### ISSUE THREAD

**Issue by infracritical** [crits/crits#574]
I have been wracking my brains out over this, and have read, re-read, and re-re-read the installation guidance(s) several times.  I have encountered several issues:

(1)  M2Crypto on GitHub no longer exists; I get a 404 error.

(2)  It appears to be assumed that you have *already* installed MongoDB and Django.  Neither of which were provided within any of the step-by-step instructions for installation onto RHEL/CentOS v6.

(3)  Even after installing Django, and reviewing the /data/crits/crits/config directory, there is NO "database.py" file; there IS, however, a "database_example.py" file.

(4)  When attempting to execute this command, I get several errors:

python
from django.utils.crypto import get_random_string as grs
print grs(50, 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)')

(4a)  I get this error message:

Python 2.7.8 (default, Aug 18 2015, 21:10:24)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from django.utils.crypto import get_random_string as grs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named django.utils.crypto

(4b)  I tried again with a concatenated command with both lines, and got this error message:

>>> from django.utils.crypto import get_random_string as grs print grs(50, 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)')
  File "<stdin>", line 1
    from django.utils.crypto import get_random_string as grs print grs(50, 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)')
                                                                 ^
SyntaxError: invalid syntax
>>>

(5)  When attempting this command:

Fix errors in the CRITs dependency installer script and then run the script:

cd /data/crits_dependencies
sed -ie 's/p7zip-9\.20\.1-2\.el6\.rf\.x86_64\.rpm/p7zip-9\.20\.1-2\.el6\.x86_64\.rpm/' install_dependencies.sh
sed -ie 's/\smatplotlib/ python-matplotlib.x86_64/' install_dependencies.sh
./install_dependencies.sh

(5a)  There appears to be nothing within this directory other than a "README.md" file indicating that this step is no longer needed/necessary.

=-=-=-=-=-=-=-=-=-=-=-=-=

/* begin soapbox rant */

Seeing that I cannot proceed forward with this installation, I have become rather disheartened that, despite all of the requirements and dependencies, that no one has either: (a) updated the installation documentation, (b) indicated any differences between versions (meaning, perform <x> for version <1.x>, and perform <y> for version <1.y>), and that (c) that there has been no further discussion about this other than implied inference that those installing this product have advanced knowledge of python, mongo and django.

Although I work on python (of which I have no issues), the combination of these 3 packages is somewhat confusing to me, and appears to be *extremely* difficult to someone who is attempting to perform this installation, even if he/she is an experienced programmer and/or systems administrator.

/* end soapbox rant */

Any assistance in this matter would be *greatly* appreciated.  And in doing so, in return, I will be more than willing to write a formalized, documented process outlining details for installation on RHEL/CentOS v6.

Last, but not least, the *main* reason for validating all of this is to implement an ICS/SCADA threat/event/incident/vulnerability tracking repository, which will be made publicly available -- free of charge -- to be used by the COI (in this case, the ICS/SCADA security/research community, as well as asset owners [electric, gas, water, etc.], and federal government [DHS]).  This is something that is desperately needed by this community, and should be made available for any intelligence or research conducted pertaining to cybersecurity, specifically ICS/SCADA security related issues.

Any questions, please feel free to send either comments here, or if you prefer to send something offline, to my email through GitHub.

Respectfully --
Bob Radvanovsky, Founder of SCADASEC

**Comment by mgoffin** [comment]
Hey Bob,

I've read through the above and I'm sorry you're having issues. I'm going to dial this back to the beginning to see if we can sort some stuff out. To start I'm going to throw out some (potentially redundant) questions and comments for you:

* Before jumping into the production installation document (I assume that's what you are using?) did you try running the bootstrap to get stuff up and running as a test? If so, how did that go? If not, it would be a good first-step.
* The RHEL supplemental guide is, from what I can tell, an account of people trying to do installs and needing extra steps. I can't speak to its accuracy as I use Ubuntu and OSX for development and deployment (I cannot stand RHEL's lack of updated core languages like Python which we require 2.7.x). Is it possible you are trying to follow this verbatim before following the production installation guide?
* The crits_dependencies repo is only kept around for older installations which were prior to our bootstrap script being around. It is as you mentioned, no longer needed except for older version installs (which we don't recommend!)
* We don't assume you have Django or MongoDB installed, but if the supplemental guide doesn't cover installing them it's most likely because it assumes you've tried the normal install process where you would get Django and MongoDB installed. This might be the hickup?
* What version of the code are you attempting to install? I only ask because the recommendation is to actually track the latest `stable` branch (currently `stable_4`). This makes upgrades as simple as "git pull" and reading the UPDATING file to see what you need to do to use the latest code.

I'll leave a question for those people who use RHEL currently: do we need the RHEL supplemental guide anymore? Can someone verify that so we can either remove it or hope that someone updates it? :)

Thanks!

**Comment by infracritical** [comment]
I ran the shell script (which BTW, implies that you're in "/data/crits" directory).  I got this error message (oh...and I forgot, I ran a yum update, which moved me up to v6.7):

(CRITsVirtualEnv)[root@server script]# ./bootstrap
Architecture: 64
Unknown distro!
Detected: centos release 6.7 (final) 6.7

I didn't RTFM the production install, and went straight to the RHEL supplemental install.

I can understand why so many folks prefer Ubuntu over RHEL/CentOS for this very reason.  I've been developing several POCs, and have had to resort to either Ubuntu 14.04 LTS or 14.10 (don't quite trust 15.x yet) to get them working.

My issue is that, as a development platform, Ubuntu is wonderful; as a production platform, ehhhh...that could be debated.  Probably one of my main reasons for using RHEL/CentOS is primarily that anyone who utilizes UNIX or LINUX in a production environment within "SCADAland" is using either OpenSolaris or RHEL; very few use a Debian-based OS (of which, I believe is the case with Ubuntu, Kali, Mint, etc. as they are all related or splintered off from Debian).

I am NOT implicating that Ubuntu (for that matter, even OS X) is/are bad choices; however, most production environments use RHEL -- more than likely -- because it is supported by Red Hat, and in working with them in the past, are fairly good about supporting their products (at least I've had a good relationship with them).

Regarding mongo and django, yes, there is no reference in there.

Regarding the version of CRITS, I simply did a "git clone" command.  Is that OK for a new install?

I have a current 64-bit copy of both Ubuntu 14.04 LTS and 14.10.  Do you have a recommendation for one over the other?  If it is this much of a hassle with RHEL/CentOS, then I will go back to Ubuntu (which was my first choice to use).

As a side note, I cannot believe that there haven't been more contributors from the RHEL/CentOS side of the house due to the abovestated reasons that I outlined.  It's sad really -- I am disappointed.

If you have a better scripted method for Ubuntu (either 14.04 LTS or 14.10), I'd love to see what you've done with your environment.  As a POC, I only have a small server with a whole whopping 2 GB of RAM, but have managed to scrounge up a 300 GB SATA drive.  I realize that the software calls for a minimum of 8 GB of RAM, but...seriously?

I am hoping that, as a POC, that I can get away with 2 GB of RAM, and understand that it will be slow......as............mmmmmmm....ooooollllllllll...aaaaaassssssssssaaaaaaaaaasssss.

Any help would be greatly appreciated.  Sorry if I sounded so negatively about this effort -- I think that it's a great concept -- which is the main reason why I'm checking this solution out.  And open source solutions, IMHO, are usually the best because of community support.

Thanks in advance for your reply, advise, et. al.

Respectfully --
Bob

**Comment by mgoffin** [comment]
Ahh. I think the problem is that it's CentOS and not true RHEL. I personally don't know what the difference between the two are outside of the basics, but RHEL has support in the bootstrap while CentOS does not. It's still possible to install on CentOS I'd assume, but it would require looking at the bootstrap for what it does when it detects a RHEL OS, and doing something similar with CentOS. Obviously not the best thing to do manually.

The 2GB of RAM should be fine. I run an entire MongoDB cluster on my MBA and it runs like a champ. The 8GB came from people saying "I have gigs of data and I need to test this out". MongoDB stores indexes in memory and will consume what it needs as the indexes grow.

**Comment by frbapolkosnik** [comment]
Bob,
You might want to try https://github.com/crits/crits/pull/576.

**Comment by dt91** [comment]
I'm having the exact same issue.  I did a fresh install of Redhat 6 and then ran yum and it updated to 6.7.  I pulled the latest code today and the bootstrap doesn't seem to detect 6.7 as a valid distro.  

cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.7 (Santiago)

**Comment by frbapolkosnik** [comment]
How about now? I just updated.

**Comment by dt91** [comment]
you updated the master branch?  I'm not seeing the change yet.  I pulled a new copy anyway, but it didn't change any behavior

**Comment by frbapolkosnik** [comment]
Nah, not yet there's PR #593 waiting for more testing (I've tested it on CentOS 6), and this is the branch where you can pull it from https://github.com/frbapolkosnik/crits/tree/patch-23
or just copy the scripts/bootstrap file and crits/contrib/mongo/mongod_start.sh from that branch.

**Comment by frbapolkosnik** [comment]
and it worked on OSX.

**Comment by dt91** [comment]
That did seem to fix it for me.  Thanks!

Eric Smead
Office 616-285-4409  •  Fax 616-977-6888
Cell    616-648-6403
