### ISSUE TITLE
Errors populating db with combine posts

### ISSUE THREAD

**Issue by cjdupreez** [crits/crits#577]
CRITS installs and runs just fine but when I run Combine and specify to output to CRITS API, Combine runs and CRITS gives me tons of HTTP 200 response codes indicating that Combine's connected to the API and is pushing it's results but when I refresh the dashboard it says I've got 0  entries in my Combine campaign. Also, when I run db.ips.count() on the crits database, I get 0. I know the problem's not with Combine as it can generate CSVs just fine, and the config has my username and API key.

Here's what I've done so far:
-Installed CRITS using the setup script provided.
-Enabled the API check box in the configuration.
-Created a Combine campaign and assigned it to my user account.

I'm running CRITS and Combine together on an Xubuntu 64-bit VM with 4 gigs of ram and 2 processors.

Thanks in advance for your assistance.

**Comment by mgoffin** [comment]
I don't know enough about Combine to help, but I can say that just because you're getting a 200 doesn't mean it's not telling you something is wrong. 200 just means we got a request to a valid page but we could be returning error responses indicative of what's wrong from the Combine end. I would work with the Combine folks to figure this out.

**Comment by cjdupreez** [comment]
Ok will do, thanks for the quick response!
