### ISSUE TITLE
No logs sent to crits.log

### ISSUE THREAD

**Issue by wzod** [crits/crits#588]
After installing CRITs using the bootstrap script as well as installing manually, it appears no logs are sent to crits.log (i.e. in /data/crits/logs/crits.log ).

Not seeing any obvious errors and permissions are set exactly as per the installation instructions (specifically followed the steps in the case of the manual install; bootstrap did not throw any errors during install).

Are folks able to see logs make their way to crits.log?  In both scenarios and regardless where I point the logs directory, there is nothing in the file (file size is 0).

**Comment by robbkrasnow** [comment]
Hi wzod,

It's not noted in the docs and I struggled with this for a while, but to get this working I had to run apache as the crits user. Running stable-4 on Ubuntu 14.04.3. To do this:

sudo vi /etc/apache2/envvars

Change the following lines:
export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data

To:
export APACHE_RUN_USER=crits
export APACHE_RUN_GROUP=crits

Or you can comment the first two lines and add the second two.

**Comment by johnfellers** [comment]
You should just have to add the crits user to the group that Apache is running as. Run ps aux and Grep for Apache or www (depending on os) to find out the group.

**Comment by jwilczek** [comment]
I followed the guide exactly and I'm still having this issue.  I've tried the suggestions of both robbkrasnow and johnfellers.  However, in monitoring /var/log/apache2/error.log I still see a permissions issue with accessing this file.

**Comment by johnfellers** [comment]
Please post the following (redact any personal infos)

-exact error messages from the error.log
-Permissions, owner & group of both the log directory and crits.log file
-the user that Apache is running as
-what it says under the crits control panel in the UI for the log directory

**Comment by jwilczek** [comment]
I think I fixed it.  I was convinced it was a permissions issue and spent all of my time digging through configs and adjusting permissions (and never even looked at the UI until you suggested to).  Turns out the path in the UI for the log directory had a relative path in it /data/crits/crits/../logs.  Not sure how I got there, but when I set that to the correct value I no longer get the permissions issue.

I'm still not seeing anything in the file though, but I also haven't entered anything through the UI.  Can someone tell me the type of data logged to this file?

Thanks for the help!
