### ISSUE TITLE
Relationships API failing in master

### ISSUE THREAD

**Issue by Lambdanaut** [crits/crits#615]
This could just be a known problem that will be worked out before merging into stable, or a known effect of the api changes, but I thought I'd bring it up anyways. 

Calls to the relationships API are returning with a 403 error in master. 

Will this be fixed, or is it intended?

**Comment by mgoffin** [comment]
This is a known change. Instead of having an exposed API designed for updating TLOs, we are actively developing API Updating capabilities. It's not fully documented because it's not done but it exposes handlers directly through the API:

https://github.com/crits/crits/blob/master/crits/core/api.py#L557

When you submit a PATCH request, you provide an `action` parameter which tells us what action you are trying to take (in this case, `forge_relationship` is what you are trying to do). Your PATCH request would be sent to the API URL for a specific TLO (ex: /api/v1/samples/[some object id]/). When you look at the handler for `forge_relationship` it will show you all of the parameters you should submit. By default, we will automatically fill out any parameters named `type_`, `id_`, and `user` as to ensure you don't abuse the API by pretending to be someone else, or forcing the API to use TLOs you don't have access to update.

**Comment by Lambdanaut** [comment]
Okay, thanks.
