### ISSUE TITLE
Performance issue with TLOs and many relationships

### ISSUE THREAD

**Issue by armtash** [crits/crits#673]
I have tested this out with the latest master commit on two servers.

As the number of relationships for a TLO grow, the amount of time it takes to add an additional relationship grows significantly.

I currently have a raw_data object, and I have forged around ~350 (out of 800) relationships with different Indicators.  I am forging these relationships using the patch API calls.

When attempting to forge a relationship using the web interface, my last request took 40 seconds to complete.  The API calls are taking just as long.

**Comment by mgoffin** [comment]
Possibly all of the looping it's doing to see if the relationship already exists to prevent duplicates.

**Comment by dsnellgrove** [comment]
We have some items with tens of thousands of relationships. To get all these on there we had to modify the code to allow bulk relationship creation. When I profiled the original code I found that the loops were actually very fast and instead the majority of the time was spent in the mongoengine module converting the mongo object to python and back again with each call; I had expected the loop to be the slow code but was wrong. We added some code to short-circuit this process during bulk creation and instead reuse the object so there was one read and one write with many relationships created in the middle.

This was quite some time ago, but before trimming the loop profile the code, I wasted a lot of time trying to optimize the wrong code at first to be disappointed the issue was in the underlying module :(

**Comment by armtash** [comment]
dsnellgrove, could you provide any more details? Can you find exactly what you changed?

**Comment by webstergd** [comment]
We I think made a similar change for the sample api calls. I think this [1]
might be what you are looking for. We stopped pushing any changes to the
API until it finished moving to the new format.

[1] https://github.com/crits/crits/pull/620

**Comment by thelok** [comment]
@dsnellgrove How did you get around the 16MB limit for documents if you have that many relationships? Unless you changed the architecture of how relationships are stored?

**Comment by dsnellgrove** [comment]
They're still squeezing into the 16MB limit. I think there was one I found that had hit it though--further additions produced errors since the indicator couldn't be saved after the edit.
