### ISSUE TITLE
Base64 encoded UTF-8 .msg subject results in "Error Uploading File"

### ISSUE THREAD

**Issue by 0xDECAFBAD** [crits/crits#678]
Disclaimer: I don't know Python/Django.

I have a .msg file that uses a Base64 encoded UTF-8 subject in the header (RFC 1342).

When I try and upload using the "Upload .msg" dialog, I get "Error Uploading File".

I hacked in some debugging code and found (truncated for brevity)
```
 <h1>UnicodeEncodeError at /emails/new/outlook/</h1>
  <pre class="exception_value">'ascii' codec can't encode character u'\xfc' in position 267: ordinal not in range(128)</pre>
  <table class="meta">

    <tbody><tr>
      <th>Request Method:</th>
      <td>POST</td>
    </tr>
    <tr>
      <th>Request URL:</th>
      <td>https://sndbox.host/emails/new/outlook/</td>
    </tr>

    <tr>
      <th>Django Version:</th>
      <td>1.6.11</td>
    </tr>

    <tr>
      <th>Exception Type:</th>
      <td>UnicodeEncodeError</td>
    </tr>


    <tr>
      <th>Exception Value:</th>
      <td><pre>'ascii' codec can't encode character u'\xfc' in position 267: ordinal not in range(128)</pre></td>
    </tr>


    <tr>
      <th>Exception Location:</th>
      <td>/usr/lib64/python2.7/email/parser.py in parsestr, line 82</td>
    </tr>

    <tr>
      <th>Python Executable:</th>
      <td>/usr/bin/python</td>
    </tr>
    <tr>
      <th>Python Version:</th>
      <td>2.7.5</td>
    </tr>
```

I "fixed" the issue by editing "/usr/lib64/python2.7/email/parser.py" and changing:

``` 
from cStringIO import StringIO
```
to 
```
from StringIO import StringIO
```
*I appreciate directly editing core/installed Python modules isn't the right way to address this issue*

As noted on: https://docs.python.org/2/library/stringio.html

> Unlike the StringIO module, this module is not able to accept Unicode strings that cannot be encoded as plain ASCII strings.

Not sure whose camp this issue lies in.

**Comment by mgoffin** [comment]
Well, I suspect that the way you fixed it might be one way, however that's modifying what looks to be python 2.7 library files which is probably bad. There might be another way to work around it in our code?

I suspect it might have something to do with this line:

https://github.com/crits/crits/blob/master/crits/emails/handlers.py#L1516

You noted that the subject is a base64 encoded UTF-8 string and we are treating it as a UTF-16 string. I can't stand this type of stuff in python because doing a massive "if/elif" block of types to try to decode with is just silly.

**Comment by dsnellgrove** [comment]
There is no reason to "guess" which codec a subject might be encoded with with an if block or a hardcoded choice. The subject will declare the encoding used before the base64 starts. https://www.rfc-editor.org/rfc/rfc1342.txt

**Comment by 0xDECAFBAD** [comment]
Going by the output in my initial post (and limited understanding), the issue is with the call to Parser.parsestr() at:

https://github.com/crits/crits/blob/master/crits/emails/handlers.py#L1528

Since the raw_header in this case contains encoded UTF-8. The subject decoding at 1516 works correctly.

A possible fix is to use the alternative parse(), as follows:
```
headers = Parser().parse(StringIO.StringIO(email.get('raw_header', '')), headersonly=True)
```
This also requires an `import StringIO`

So far, this seems to solve the issue. I can't comment on the sanity of the solution though.

**Comment by apolkosnik** [comment]
io is already imported, the forward-compatible way is to use io rather than StringIO.

Try the following:
headers = Parser().parse(io.StringIO(email.get('raw_header', '')), headersonly=True)

**Comment by 0xDECAFBAD** [comment]
Yup, that works :)

**Comment by packet-rat** [comment]
Just want to remind everyone that the decode issues may be from INTENTIONAL illegal UTF-8 character representations (usually Subject Lines) to evade signature based detection (e.g.: Ironport rules).  So...it not a question of "knowing" the correct encode/decode, you will get this error when parsing intentionally malformed encodings in string IOCs.

Patrick Maroney
Cell: (609)841-5104


On Jan 13, 2016, at 5:23 PM, 0xDECAFBAD <notifications@github.com> wrote:

Yup, that works :)
