### ISSUE TITLE
Getting an error while trying to delete Indicator Actions

### ISSUE THREAD

**Issue by gleblanc1783** [crits/crits#699]
Currently using 'Release 3.1.0' 

We have been having trouble while trying to delete Indicator actions. I noticed while taking a peek at the HTTP request headers when performing an 'action_remove' that it simply only passes a datetime string to CRITs in order to find the correct action to delete. The thing is, we are automatically uploading IoCs to CRITs via the API (and MongoDB) and the datetime on the actions will be **same** for all actions in a specific Indicator Object. There currently is no way to add an Indicator Action to an Indicator TLO via the API so we have to get creative and manually add them via MongoDB.

Is there anything in the works to fix this? I know a possible solution on our end will be to simply increment the values of the actions to make sure they are unique.

**Comment by mgoffin** [comment]
I would recommend moving to tracking stable_4. There are countless enhancements and fixes in there and will most likely solve your problem.

**Comment by gleblanc1783** [comment]
Alright so after a little bit of understanding how this works, I ended up 'fixing it' for our own environment. Instead of passing the datetime to the handler I ended up just passing the actual action_type itself. Works like a charm. **Note:** If you have two actions of the same type it would probably delete the first iteration of that specific action. In our environment we make sure we don't have two of the same actions.

**Comment by gleblanc1783** [comment]
Thanks Mike! I'll look into it! (And will probably do that ASAP).

**Comment by armtash** [comment]
It is interesting that you also try to prevent duplicate actions.  At my organization, we have modified the actions to prevent duplicates from being added.  @mgoffin Would you be interested in changes that prevent duplicate actions from being created?

**Comment by gleblanc1783** [comment]
I'd definitely be interested in seeing what you're doing. We use actions sort of as "switches" for determining what happens with these Indicators (Are we blocking them at the firewall? DNS? Alerting via our SIEM?) -- all via actions. Unintended and possibly catastrophic things would happen if there were more than one :)

**Comment by mgoffin** [comment]
We don't prevent duplicate actions mainly because people like to track historically what sort of actions they've taken on an Indicator. For example, if I have an action of "monitor" and I use it from 1/1/2016-2/1/2016 that would be one action. If I then go back and want to monitor it again from 2/2/2016-3/1/2016 there are two options for me:

1) Edit the existing action with the new date range which causes me to lose the historical record of my original monitoring.
2) Create a new action with the same action type and the new date range which preserves my original action but notes that I am now performing that action again.

A lot of people prefer the latter because of the historical context.

**Comment by armtash** [comment]
Indeed the historical context is quite valuable.  Thanks for your input.

**Comment by brlogan** [comment]
In our environment, I've added some code that doesn't allow a new action to be added if there exists an Active action of the same type.  This allows us to have historical context while also preventing conflicting actions.
