### ISSUE TITLE
Signatures and related Campaigns

### ISSUE THREAD

**Issue by ericwentz** [crits/crits#904]
Is there a way either via the web UI or the API to associate a signature with a campaign or multiple campaigns?  The signature summary page has a column for campaign, but I do not see any way via either method to create this entry.  I looked at the record structure in the mongo database and there *is* a field to hold a campaign, I just don't see any way to add it.

I searched the issues list and could not find any other references to this question.

Thanks
Eric

**Comment by mgoffin** [comment]
Go to signature details page, go to the Campaigns section and add a Campaign.

**Comment by ericwentz** [comment]
Thanks, Mike - yeah, just found that one - what about via the API? Is this another "patch" function?

**Comment by ericwentz** [comment]
Quick update - I tried a "forge_relationship" call and while that was successful and the relationship showed up in the signature detail page - it was under relationships (duh) and *not* under the campaigns section.

**Comment by mgoffin** [comment]
The list of exposed PATCH handlers is here:

https://github.com/crits/crits/blob/master/crits/core/api.py#L580

Looks like the stuff for adding/editing/removing an attributed campaign via PATCH hasn't been exposed yet.

**Comment by ericwentz** [comment]
Hmmm - that's unfortunate - I may play with this and maybe issue a PR on this feature - I'll see if I can do this without breaking other things.  Thanks for checking.

**Comment by mgoffin** [comment]
No problem! The process for exposing a handler for PATCH is fairly simple.

- Import the appropriate handlers page in the section I linked above, and add the handler to the dictionary with a key that would be the `action` you pass into your PATCH request. In this case, since this is something you can do to multiple TLOs, it would go in the `Common` section.
- Modify the handler in question so that the arguments `type_`, `id_`, `user`, and `kwargs**` are there. In some cases they are there already but under a different argument name. It needs to be renamed so we can override them appropriately.
  - This will require a look over that handler so that any instances of the old argument names are replaced with the new argument names.
  - This will also require searching the code base in both this repo and crits_services to see if it's being called anywhere else and adjusting the way it's called to accommodate for the new argument names.
